///////////////////////////////////////////////////////////
//  Column.cs
//  Implementation of the Class Column
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:47:57
//  Original author: oalt
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleRDBMS;
namespace LL.MDE.DataModels.SimpleRDBMS {
	public class Column : RModelElement {

		public String type;

		public Table owner;
		public List<Key> key = new List<Key>();
		public List<ForeignKey> foreinKey = new List<ForeignKey>(); 

		public Column(){

		}

	

	}//end Column

}//end namespace SimpleRDBMS