///////////////////////////////////////////////////////////
//  ForeignKey.cs
//  Implementation of the Class ForeignKey
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:48:00
//  Original author: oalt
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleRDBMS;
namespace LL.MDE.DataModels.SimpleRDBMS {
	public class ForeignKey : RModelElement
	{

		public Table owner;
		public List<Key> key  = new List<Key>();
		public List<Column> column = new List<Column>();

		public ForeignKey(){

		}


	}//end ForeignKey

}//end namespace SimpleRDBMS