///////////////////////////////////////////////////////////
//  Key.cs
//  Implementation of the Class Key
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:48:02
//  Original author: oalt
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleRDBMS;
namespace LL.MDE.DataModels.SimpleRDBMS {
	public class Key : RModelElement
	{

		public Table owner;
		public List<Column> column = new List<Column>();
		public List<ForeignKey> refersToOposite = new List<ForeignKey>();

		public Key(){

		}

		

	}//end Key

}//end namespace SimpleRDBMS