///////////////////////////////////////////////////////////
//  RModelElement.cs
//  Implementation of the Class RModelElement
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:48:04
//  Original author: oalt
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleRDBMS;
namespace LL.MDE.DataModels.SimpleRDBMS {
	public class RModelElement {

		public String kind;
        public String name;

		public RModelElement(){

		}

		

	}//end RModelElement

}//end namespace SimpleRDBMS