///////////////////////////////////////////////////////////
//  Schema.cs
//  Implementation of the Class Schema
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:48:06
//  Original author: oalt
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleRDBMS;
namespace LL.MDE.DataModels.SimpleRDBMS {
	public class Schema : RModelElement {

		public List<Table> tables = new List<Table>();

		public Schema(){

		}


	}//end Schema

}//end namespace SimpleRDBMS