///////////////////////////////////////////////////////////
//  Association.cs
//  Implementation of the Class Association
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:39
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public class Association : PackageElement
	{

	    public Class source;
	    public Class destination;

		public Association(){

		}

		~Association(){

		}

	}//end Association

}//end namespace SimpleUML