///////////////////////////////////////////////////////////
//  Boolean.cs
//  Implementation of the Class Boolean
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:39
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace LL.MDE.DataModels.SimpleUML {
	public class Boolean {

		public Boolean(){

		}

		~Boolean(){

		}

	}//end Boolean

}//end namespace SimpleUML