///////////////////////////////////////////////////////////
//  Classifier.cs
//  Implementation of the Class Classifier
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:39
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public abstract class Classifier : PackageElement {

		public Boolean isAbstract;

		public Attribute typeOpposite;

		public Classifier(){

		}


	}//end Classifier

}//end namespace SimpleUML