///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:39
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public class Class : Classifier {

		public List<Class> general = new List<Class>();
		public List<Class> generalOpposite = new List<Class>();
		public List<Association> reverse = new List<Association>();
		public List<Association> forward = new List<Association>();
		public List<Attribute> attribute = new List<Attribute>();

		public Class(){

		}

	

	}//end Class

}//end namespace SimpleUML