///////////////////////////////////////////////////////////
//  PackageElement.cs
//  Implementation of the Class PackageElement
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:40
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public abstract class PackageElement : UMLModelElement {

        public Package @namespace;

		public PackageElement(){

		}

	}//end PackageElement

}//end namespace SimpleUML