///////////////////////////////////////////////////////////
//  Package.cs
//  Implementation of the Class Package
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:39
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public class Package : UMLModelElement {

		List<PackageElement> elements = new List<PackageElement>();

		public Package()
		{

		}


	}//end Package

}//end namespace SimpleUML