///////////////////////////////////////////////////////////
//  PrimitiveDataType.cs
//  Implementation of the Class PrimitiveDataType
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:40
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using LL.MDE.DataModels.SimpleUML;
namespace LL.MDE.DataModels.SimpleUML {
	public class PrimitiveDataType : Classifier {

		public PrimitiveDataType(){

		}

		~PrimitiveDataType(){

		}

	}//end PrimitiveDataType

}//end namespace SimpleUML