///////////////////////////////////////////////////////////
//  UMLModelElement.cs
//  Implementation of the Class UMLModelElement
//  Generated by Enterprise Architect
//  Created on:      13-Okt-2016 13:01:48
///////////////////////////////////////////////////////////

using System;

namespace LL.MDE.DataModels.SimpleUML
{
	public abstract class UMLModelElement
	{

		public String kind;
		public String name;

		public UMLModelElement()
		{

		}


	}//end UMLModelElement

}//end namespace SimpleUML